version: "3.3"

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  app:
    build: .
    volumes:
      - ./db:/app/db/
    ports:
      - "8000:80"
